;;;
; xiao-esp32s3-camera-webserver-pio
;
; Copyright (C) 2025, GPL-3.0-or-later, Nicolas Jeanmonod, ouilogique.com
;;

[platformio]
extra_configs =
    ./*user_settings.ini

[env]
monitor_speed = 115200
upload_speed = 1000000
framework = arduino
build_flags =
    -D BAUD_RATE=${this.monitor_speed}
lib_deps =
  espressif/esp32-camera@^2.0.4
  # SD/MMC and FS libraries are included in Arduino-ESP32, so they do not need to be listed explicitly
monitor_port = ${this.upload_port}

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
board_build.partitions = src/partitions.csv
